/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import tests.ColorTest;
	import tests.DisplayObjectContainerTest;
	import tests.DisplayObjectTest;
	import tests.EventTest;
	import tests.JugglerTest;
	import tests.MovieClipTest;
	import tests.QuadTest;
	import tests.TextureAtlasTest;
	import tests.TextureTest;
	import tests.TweenTest;
	import tests.UtilsTest;
	import tests.VertexDataTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var tests_EventTest_obj:tests.EventTest;
		private var tests_TextureAtlasTest_obj:tests.TextureAtlasTest;
		private var tests_DisplayObjectContainerTest_obj:tests.DisplayObjectContainerTest;
		private var tests_TweenTest_obj:tests.TweenTest;
		private var tests_QuadTest_obj:tests.QuadTest;
		private var tests_ColorTest_obj:tests.ColorTest;
		private var tests_JugglerTest_obj:tests.JugglerTest;
		private var tests_MovieClipTest_obj:tests.MovieClipTest;
		private var tests_DisplayObjectTest_obj:tests.DisplayObjectTest;
		private var tests_UtilsTest_obj:tests.UtilsTest;
		private var tests_TextureTest_obj:tests.TextureTest;
		private var tests_VertexDataTest_obj:tests.VertexDataTest;
	}
}