/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
    import flash.display.Sprite;
    
    import tests.animation.DelayedCallTest;
    import tests.animation.JugglerTest;
    import tests.animation.TweenTest;
    import tests.display.BlendModeTest;
    import tests.display.DisplayObjectContainerTest;
    import tests.display.DisplayObjectTest;
    import tests.display.MovieClipTest;
    import tests.display.QuadTest;
    import tests.events.EventTest;
    import tests.textures.TextureAtlasTest;
    import tests.textures.TextureTest;
    import tests.utils.AssetManagerTest;
    import tests.utils.ColorTest;
    import tests.utils.RectangleUtilTest;
    import tests.utils.UtilsTest;
    import tests.utils.VertexDataTest;
    
    public class FlexUnitCompilerApplication extends Sprite
    {
        private var tests_AssetManagerTest_obj:tests.utils.AssetManagerTest;
        private var tests_BlendModeTest_obj:tests.display.BlendModeTest;
        private var tests_MovieClipTest_obj:tests.display.MovieClipTest;
        private var tests_TextureTest_obj:tests.textures.TextureTest;
        private var tests_VertexDataTest_obj:tests.utils.VertexDataTest;
        private var tests_TweenTest_obj:tests.animation.TweenTest;
        private var tests_ColorTest_obj:tests.utils.ColorTest;
        private var tests_TextureAtlasTest_obj:tests.textures.TextureAtlasTest;
        private var tests_RectangleUtilTest_obj:tests.utils.RectangleUtilTest;
        private var tests_DisplayObjectContainerTest_obj:tests.display.DisplayObjectContainerTest;
        private var tests_QuadTest_obj:tests.display.QuadTest;
        private var tests_UtilsTest_obj:tests.utils.UtilsTest;
        private var tests_DelayedCallTest_obj:tests.animation.DelayedCallTest;
        private var tests_DisplayObjectTest_obj:tests.display.DisplayObjectTest;
        private var tests_JugglerTest_obj:tests.animation.JugglerTest;
        private var tests_EventTest_obj:tests.events.EventTest;
    }
}