name: Compile SWF

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - uses: joshtynjala/setup-adobe-air-action@v2
        with:
          air-version: "51.2"
          accept-license: true

      - name: Run Tests
        shell: bash
        run: tests/run.sh

      - name: Upload golden image failures
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: golden-failures
          path: tests/out/golden-failures
          if-no-files-found: ignore
          
